os:
  - linux
  - osx
  - windows
language: rust
rust:
  - stable
  - beta
  - nightly
cache: rust
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo test --all --verbose
  - rustup component add clippy rustfmt &&
    cargo clippy
