os:
  - linux
  - osx
  - windows
language: rust
rust:
  - stable
  - beta
  - nightly
cache: rust
matrix:
  allow_failures:
    - rust: nightly
before_script: # Use the msvc toolchain of rust
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup toolchain add $TRAVIS_RUST_VERSION-x86_64-pc-windows-msvc && rustup default $TRAVIS_RUST_VERSION-x86_64-pc-windows-msvc ; fi
script:
  - cargo test --all --verbose
  # Note: Whilst Travis says to install these in the before_script,
  # on nightly the install command fails
  # so the install happens after tests so nightly tests are still ran
  - rustup component add clippy rustfmt
  - cargo clippy 
