[package]

name = "sys-info-rs"
version = "0.0.1"
authors = ["Siyu Wang <FillZpp.pub@gmail.com"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/FillZpp/sys-info-rs"
homepage = "https://github.com/FillZpp/sys-info-rs"
description = """
Get system information in Rust.
"""

[dependencies.info]
path = "info"
version = "*"

