[package]

name = "sys-info"
version = "0.1.1"
authors = ["Siyu Wang <FillZpp.pub@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/FillZpp/sys-info-rs"
documentation = "http://docs.fillzpp.org/sys-info-rs/sys-info/"
description = """
Get system information in Rust.
"""

links = "info"
build = "build.rs"

[lib]
name = "sys-info"
path = "lib.rs"

[build-dependencies]
gcc = "*"


